name = "meraki"
main = "worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

# Custom domain route
[[routes]]
pattern = "meraki.onenecklab.com/*"
zone_name = "onenecklab.com"

# KV namespaces
[[kv_namespaces]]
binding = "MERAKI_CALL_LOGS"
id = "cb2ff45802034ac386da338aab965bd0"

[[kv_namespaces]]
binding = "MERAKI_CUSTOMERS"
id = "66d08564b8ca44c69cfb7aaa945a09f1"

[[kv_namespaces]]
binding = "MERAKI_RUNS"
id = "58779e61e222495392c88714f63d2a4f"

[[kv_namespaces]]
binding = "MERAKI_SECRETS"
id = "32f4f933615a4ff4bcb709cc514b034e"

[[kv_namespaces]]
binding = "MERAKI_WEEKLY"
id = "20438173022545b2b65c64d03bea5627"

[[kv_namespaces]]
binding = "SNMP_RESULTS"
id = "e9b16cc4aa6e444e869d9daef41dcc6f"

[[kv_namespaces]]
binding = "SNMP_TARGETS"
id = "73e7fa893fe047ae920615e9b8141466"

# Non-secret runtime vars
[vars]
ADMIN_EMAIL_DOMAINS = "ussignal.com"
EMAIL_FROM_NAME = "US Signal Meraki Portal"
BREVO_SENDER_EMAIL = "meraki-ussignal@onenecklab.com"
FROM_EMAIL = "meraki-ussignal@onenecklab.com"

# Cron trigger for steady call generation
[triggers]
crons = ["0 */6 * * *"]

